routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ContactController@dashboard');

Route::get('contacts/ajax', 'ContactController@ajax');
Route::get('contacts/getLatLng', 'ContactController@getLatLng');
Route::resource('contacts', 'ContactController');

app/Models/Address.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Address extends Model
{
    protected $fillable = [
        'contact_id',
        'code',
        'uf',
        'city',
        'district',
        'street',
        'number',
        'lat',
        'lng'
    ];

    public function setCodeAttribute($value)
    {
        $this->attributes['code'] = str_replace([' ', '(', ')', '-'], '', $value);
    }

    protected $table = 'address';

    /**
     * @return array[] Validation rules
     */
    public $rules =  [
        'contact_id' => 'required|exists:contacts,id',
        'code' => 'required|numeric',
        'uf' => 'string|nullable',
        'city' => 'string|nullable',
        'district' => 'string|nullable',
        'street' => 'string|nullable',
        'number' => 'numeric|nullable',
        'lat' => 'string|nullable',
        'lng' => 'string|nullable'
    ];
}

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $fillable = [
        'name',
        'email',
        'telephone'
    ];

    public function getTelephoneMaskedAttribute() {
        $value = $this->telephone;
        if (strlen($value) < 10) {
            return "--";
        }
        $ddd = substr($value, 0, 2);
        $final = substr($value, -4);
        return '('.$ddd.') '.str_replace([$ddd, $final], '', $value).'-'.$final;
    }

    public function setTelephoneAttribute($value) {
        $this->attributes['telephone'] = str_replace([' ', '(', ')', '-'], '', $value);
    }

    protected $table = 'contacts';

    /**
     * @return array[] Validation rules
     */
    public $rules =  [
            'name' => 'nullable|string',
            'email' => 'required|email|unique:contacts,email',
            'telephone' => 'numeric|nullable',
    ];

    public function address()
    {
        return $this->hasMany(Address::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contact;
use Illuminate\Http\Request;
use App\Repositories\ContactRepository;
use Validator;
use DB;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $repository = new ContactRepository;
        return view('contact.index', ['contacts' => $repository->list()->get()]);
    }

    public function dashboard()
    {
        return view('contact.dashboard');
    }

    public function ajax()
    {
        $repository = new ContactRepository;
        return $repository->list()->select([
            DB::raw('DATE_FORMAT(created_at, "%Y-%m-%d") as date'),
            DB::raw('count(*) as total')
        ])
        ->groupBy(DB::raw('DATE_FORMAT(created_at, "%Y-%m-%d")'))
        ->get()
        ->pluck('total', 'date')
        ->toJson();
    }

    public function getLatLng()
    {
        $repository = new ContactRepository;
        $arrLatLng = [];
        foreach ($repository->list()->get() as $contact) {
            $arrLatLng[] = $contact->toArray()+$contact->address[0]->toArray();
            
        }
        return json_encode($arrLatLng);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        return view('contact.form', [
            'name'=>'', 
            'email'=>'', 
            'telephone'=>'',
            'address' => [[
                'code' => '',
                'uf' => '',
                'city' => '',
                'district' => '',
                'street' => '',
                'number' => '',
                'lat' => '',
                'lng' => '',
            ]]
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $arrAddress = Request(['code', 'uf', 'city', 'district', 'street', 'number', 'lat', 'lng']);
            $repository = new ContactRepository;
            $repository->save(Request(['name', 'email', 'telephone'])+['address' => $arrAddress]);
            return redirect('contacts')->with('success', 'save success');
        } catch(\Exception $e) {            
            return back()->withErrors(json_decode($e->getMessage()))->withInput(Request(['name', 'email', 'telephone'])+['address' => $arrAddress]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function edit(Contact $contact)
    {
        return view('contact.form', $contact->toArray()+['address' => $contact->address]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Contact $contact)
    {
        try {
            $arrAddress = Request(['code', 'uf', 'city', 'district', 'street', 'number', 'lat', 'lng']);
            $repository = new ContactRepository;
            $repository->save(Request(['name', 'email', 'telephone'])+['id' => $contact->id]+['address' => $arrAddress]);
            return redirect('contacts')->with('success', 'save success');
        } catch(\Exception $e) {            
            return back()->withErrors(json_decode($e->getMessage()))->withInput(Request(['name', 'email', 'telephone']));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contact $contact)
    {
        $repository = new ContactRepository;
        $repository->delete($contact);        
        return redirect('contacts')->with('success','Product has been  deleted');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/contact/dashboard.blade.php
@extends('layouts.default')
@section('title', 'Contacts')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div style="display: block;margin:0 auto;max-width:950px;" id="gchart" data-title="Cadastros por dia" data-url="{{url('contacts/ajax')}}"></div>
        </div>
        <div class="col-md-6">
            <div id="chart_div" data-title="Cadastros por dia" data-url="{{url('contacts/ajax')}}"></div>
        </div>
        <div class="col-md-6">
            <div id="map" style="width=100%;height:450px" data-url="{{url('contacts/getLatLng')}}"></div>
        </div>
    </div>

@stop

@push('scripts')
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js">
    </script>
    <script 
src="https://maps.googleapis.com/maps/api/js?libraries=visualization&key={{env('GOOGLE_API_KEY')}}">
    </script>

    <script type="text/javascript">
        google.charts.load('current', {'packages':['calendar']});      
        google.charts.setOnLoadCallback(drawDayChart);

        function drawDayChart() {
            var dataTable = new google.visualization.DataTable();
            dataTable.addColumn({ type: 'date', id: 'Date' });
            dataTable.addColumn({ type: 'number', id: 'Qtd' });                
            $.ajax({
                url: $('#gchart').attr('data-url')
            }).done(function(data) { 
                arrRows=[];                       
                $.each(JSON.parse(data), function(day, total){
                    arrData = day.split('-');
                    arrRows.push([new Date(arrData[0], arrData[1], arrData[2]), total]);
                });                    
                dataTable.addRows(arrRows);
                var chart = new google.visualization.Calendar(document.getElementById('gchart'));
                var options = {
                    title: $('#gchart').attr('data-title'),
                    
                    calendar: {
                        daysOfWeek: 'DSTQQSS',
                    }
                };
                chart.draw(dataTable, options);
            });           
        }

        google.charts.load('current', {'packages':['corechart', 'bar', 'line']});
        google.charts.setOnLoadCallback(drawLines);            

        function drawLines() {
            var dataTable = new google.visualization.DataTable();
            dataTable.addColumn({ type: 'date', id: 'Date' });
            dataTable.addColumn({ type: 'number', id: 'Qtd' });  
            $.ajax({
                url: $('#chart_div').attr('data-url')
            }).done(function(data) { 
                arrRows=[];                       
                $.each(JSON.parse(data), function(day, total){
                    arrData = day.split('-');
                    arrRows.push([new Date(arrData[0], arrData[1], arrData[2]), total]);
                });                    
                dataTable.addRows(arrRows);
                var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
                var options = {
                    title: $('#chart_div').attr('data-title'),
                    
                };
                chart.draw(dataTable, options);
                
            });
        }

    </script>
    <script>
        $().ready(function(){
            $('#map').each(function(){
                $url = $(this).attr('data-url');
                $id = $(this).attr('id');
                var map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 5,                
                });

                $.ajax({
                url: $url
                }).done(function(data) { 
                    markers=[];
                    heatMarks=[];
                    $.each(JSON.parse(data), function(i, location){
                        latLng = {lat:Number(location.lat), lng:Number(location.lng)};
                        var contentString = '<div id="content">'+
                        '<div id="siteNotice">'+
                        '</div>'+
                        '<p style="margin:0">'+'<b>Cep:&nbsp;</b>'+location.code+'</p>'+
                        '<p style="margin:0">'+'<b>UF:&nbsp;</b>'+location.uf+'</p>'+
                        '<p style="margin:0">'+'<b>City:&nbsp;</b>'+location.city+'</p>'+
                        '<p style="margin:0">'+'<b>District:&nbsp;</b>'+location.district+'</p>'+
                        '<p style="margin:0">'+'<b>Email:&nbsp;</b>'+location.email+'</p>'+
                        '</div>';

                        var infowindow = new google.maps.InfoWindow({
                            content: contentString,
                            maxWidth: 200
                        });
                        
                        mark = new google.maps.Marker({
                                position: latLng,
                                title:location.name                           
                        });
                        mark.addListener('click', function() {                            
                            infowindow.open(map, markers[i]);                            
                        });
                        
                        map.setCenter(latLng);
                        markers.push(mark);
                        heatMarks.push(new google.maps.LatLng(Number(location.lat), Number(location.lng)))
                    });                    

                    //var markerCluster = new MarkerClusterer(map, markers,
                //{imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});

                    heatmap = new google.maps.visualization.HeatmapLayer({
                        data: heatMarks,
                        map: map
                    });

                    
                });
            });
        });
    </script>
@endpush

resources/views/contact/form.blade.php
@extends('layouts.default')
@section('title', "Create Contacts")
@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    @if(isset($id))
        @section('title', "Edit Contacts")
        <form method="post" action="{{action('ContactController@update', $id)}}">
        <input name="_method" type="hidden" value="PATCH">
    @else
        <form method="post" action="{{url('contacts')}}">
    @endif

    {{csrf_field()}}
    <div class="form-group">
        <label for="name">Name:</label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1"><i class="fa fa-user-tie"></i></span>
            </div>
            @include('partials.input', ['nameId' => 'name', 'value' => $name])            
        </div>
    </div>

    <div class="form-group">
        <label for="email">Email:</label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1"><i class="fa fa-at"></i></span>
            </div>
            @include('partials.input', ['nameId' => 'email', 'value' => $email, 'attr' => ['required']])            
        </div>    
    </div>

    <div class="form-group">
        <label for="telephone">Telephone:</label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1"><i class="fa fa-phone"></i></span>
            </div>
            @include('partials.input', ['nameId' => 'telephone', 'value' => $telephone])
        </div>
    </div>

    
    @include('partials.address', $address[0])
    

    <div class="col-xs-12 text-right">  
        <a class="btn btn-danger" href="{{url('contacts')}}"><i class="fa fa-arrow-circle-left"></i>&nbsp;Voltar</a>
        <button class="btn btn-success" type="submit"><i class="fa fa-save"></i>&nbsp;Save</button>
    </div>

</form>
@stop

resources/views/contact/index.blade.php
@extends('layouts.default')
@section('title', 'Contacts')
@section('content')
    @if (\Session::has('success'))
        <div class="alert alert-success">
        <p>{{ \Session::get('success') }}</p>
        </div>
    @endif

    <div class="col-md-12 text-right">
        <a href="{{url('contacts/create')}}" class="btn btn-primary"><i class="fa fa-plus-circle"></i>&nbsp;Add</a>
    </div>
    <div class="col-md-12">
        <table class="table table-striped mt-2">
            <thead>
                <tr>
                    <th class="d-none d-sm-block">Name</th>
                    <th style="max-width: 150px">Email</th>
                    <th class="d-none d-sm-block">Telephone</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($contacts as $contact)
                    <tr>
                        <td class="d-none d-sm-block">{{$contact->name}}</td>
                        <td style="max-width: 200px;overflow:hidden;">{{$contact->email}}</td>
                        <td class="d-none d-sm-block">{{$contact->telephone_masked}}</td>
                        <td>
                            <a style="display:inline-block" class="btn btn-light" href="{{action('ContactController@edit', $contact['id'])}}"><i class="fa fa-edit"></i></a>
                            <form style="display:inline-block" action="{{action('ContactController@destroy', $contact['id'])}}" method="post">
                            {{csrf_field()}}
                            <input name="_method" type="hidden" value="DELETE">
                            <button class="btn btn-danger" type="submit"><i class="fa fa-trash"></i></button>
                            </form>                
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@stop

resources/views/layouts/default.blade.php
<html>
    <head>
        <title>{{env('APP_NAME')}} - @yield('title')</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar  navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{{url('')}}"><i class="fa fa-address-book"></i></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
                
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item {{(URL::current() == url(''))? 'active' : '' }}">
                        <a class="nav-link" href="{{url('')}}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item {{(strstr(URL::current(), url('contacts')))? 'active' : '' }}">
                        <a class="nav-link" href="{{url('contacts')}}">Contacts</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container mt-5">
            @yield('content')
        </div>

        <script src="{{url('/js/jquery-3.3.1.min.js')}}"></script>
        
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="https://igorescobar.github.io/jQuery-Mask-Plugin/js/jquery.mask.min.js"></script>        
        @stack('scripts')
        <script>
            $().ready(function(){
                $('.telephone')
                .mask('(00) 0000-00009')
                .blur(function(){
                    var phone, element;
                    element = $(this);
                    element.unmask();
                    phone = element.val().replace(/\D/g, '');
                    if(phone.length > 10) {
                        element.mask("(99) 99999-9999");
                    } else {
                        element.mask("(99) 9999-99999");
                    }
                }).each(function(){
                    var phone, element;
                    element = $(this);
                    element.unmask();
                    phone = element.val().replace(/\D/g, '');
                    if(phone.length > 10) {
                        element.mask("(99) 99999-9999");
                    } else {
                        element.mask("(99) 9999-99999");
                    }
                });
            });
        </script>
    </body>
</html>

resources/views/partials/address.blade.php
<div class="row">
    <div class="col-xs-12 col-md-3">
        <div class="form-group">
            <label for="code">Cep:</label>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="fa fa-compass"></i></span>
                </div>
                @include('partials.input', ['nameId' => 'code', 'value' => $code, 'attr' => ['required']])
            </div>
        </div>
    </div>
    <div class="col-md-3 col-xs-12">
        <div class="form-group">
            <label for="uf">Uf:</label>
            @include('partials.input', ['nameId' => 'uf', 'value' => $uf, 'attr' => ['readonly']])
        </div>
    </div>
    <div class="col-md-3 col-xs-12">
        <div class="form-group">
            <label for="city">City:</label>
            @include('partials.input', ['nameId' => 'city', 'value' => $city, 'attr' => ['readonly']])
        </div>
    </div>
    <div class="col-md-3 col-xs-12">
        <div class="form-group">
            <label for="city">District:</label>
            @include('partials.input', ['nameId' => 'district', 'value' => $district, 'attr' => ['readonly']])
        </div>
    </div>

    <div class="col-md-8">
        <div class="form-group">
            <label for="street">Street:</label>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="fa fa-road"></i></span>
                </div>
                @include('partials.input', ['nameId' => 'street', 'value' => $street])
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="number">Number:</label>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="fa fa-sign"></i></span>
                </div>
                @include('partials.input', ['nameId' => 'number', 'value' => $number])
            </div>
        </div>
    </div>
    @include('partials.input', ['nameId' => 'lat', 'value' => $lat, 'type' => 'hidden'])
    @include('partials.input', ['nameId' => 'lng', 'value' => $lng, 'type' => 'hidden'])
</div>

@push('scripts')
<script>
    $().ready(function(){
        $('.code').mask('00000-000').blur(function(){
            var $val = $(this).val();
            $content = $(this).parents('.row');
            $.ajax({
                url: 'https://maps.googleapis.com/maps/api/geocode/json?address='+$val+"&key={{env('GOOGLE_API_KEY')}}"
            }).done(function(data) {
                $content.find('.uf').val(data.results[0].address_components[3].short_name);
                $content.find('.city').val(data.results[0].address_components[2].short_name);
                $content.find('.district').val(data.results[0].address_components[1].short_name);
                $content.find('.lat').val(data.results[0].geometry.location.lat);
                $content.find('.lng').val(data.results[0].geometry.location.lng);                
                $content.find('.street').focus();
            });
        });        
    });
</script>
@endpush

resources/views/partials/input.blade.php
<input 
name="{{$nameId}}" 
id="{{$nameId}}" 
type="{{(isset($type))? $type : '' }}" 
class="form-control {{$nameId}}" 
value="{{(old($nameId))?old($nameId):$value}}"
{{(isset($attr) && is_array($attr))?implode(' ', $attr):''}}>